version: "3.8"

volumes:
  grafana-data: {}
  bootstrap-scripts: {}

networks:
  monitoring-net:
    driver: bridge

services:
  # Grafana for data visualization
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "${GRAFANA_PORT}:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - monitoring-net
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}

  # New service to copy bootstrap scripts into the named volume
  bootstrap-init:
    image: alpine:latest
    container_name: bootstrap-init
    restart: "no"
    # Portainer checks out the Git repo to /stack
    working_dir: /stack
    volumes:
      # Mount the bootstrap scripts from the Git checkout (read-only)
      - ./clickhouse_bootstrap:/stack/clickhouse_bootstrap:ro
      # Mount the named volume to copy the scripts TO (writable)
      - bootstrap-scripts:/bootstrap
    # Command to copy the scripts from the git source to the named volume
    command: cp -r /stack/clickhouse_bootstrap/. /bootstrap/

  # ClickHouse database with conditional S3 storage
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-server
    hostname: clickhouse-server
    restart: unless-stopped
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ${CLICKHOUSE_DATA_PATH}:/var/lib/clickhouse
      # Mount the named volume that now contains the bootstrap scripts
      - bootstrap-scripts:/clickhouse_bootstrap
    networks:
      - monitoring-net
    environment:
      CLICKHOUSE_USER: ${CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
      S3_HOST: ${S3_HOST:-}
      S3_BUCKET: ${S3_BUCKET:-}
      S3_PREFIX: ${S3_PREFIX:-}
      KEY: ${KEY:-}
      SECRET: ${SECRET:-}
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    entrypoint: /clickhouse_bootstrap/entrypoint.sh
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8123/ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    # Make sure clickhouse waits for the scripts to be copied
    depends_on:
      bootstrap-init:
        condition: service_completed_successfully

  # Gigapipe service in "init" mode
  gigapipe-init:
    image: gigapipe:latest
    container_name: gigapipe-init
    restart: "no"
    networks:
      - monitoring-net
    environment:
      CLICKHOUSE_SERVER: "clickhouse-server"
      CLICKHOUSE_AUTH: "${CLICKHOUSE_USER}:${CLICKHOUSE_PASSWORD}"
      PORT: "9080"
      MODE: "init_only"
    depends_on:
      clickhouse:
        condition: service_healthy

  # Gigapipe service in "writer" mode
  gigapipe-writer:
    image: gigapipe:latest
    container_name: gigapipe-writer
    hostname: gigapipe-writer
    restart: unless-stopped
    ports:
      - "${WRITER_PORT}:9080"
    networks:
      - monitoring-net
    environment:
      CLICKHOUSE_SERVER: "clickhouse-server"
      CLICKHOUSE_AUTH: "${CLICKHOUSE_USER}:${CLICKHOUSE_PASSWORD}"
      PORT: "9080"
      MODE: "writer"
    depends_on:
      gigapipe-init:
        condition: service_completed_successfully

  # Gigapipe service in "reader" mode
  gigapipe-reader:
    image: gigapipe:latest
    container_name: gigapipe-reader
    hostname: gigapipe-reader
    restart: unless-stopped
    ports:
      - "${READER_PORT}:9080"
    networks:
      - monitoring-net
    environment:
      CLICKHOUSE_SERVER: "clickhouse-server"
      CLICKHOUSE_AUTH: "${CLICKHOUSE_USER}:${CLICKHOUSE_PASSWORD}"
      PORT: "9080"
      MODE: "reader"
    depends_on:
      gigapipe-init:
        condition: service_completed_successfully
