version: '3.8'

services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "{{ PORT }}:80"
    command: >
      sh -c '
        echo "<!DOCTYPE html><html><head><title>Welcome to Nginx!</title></head><body><h1>Hello from my Nginx container!</h1><p>This page is served by the Nginx container deployed via a Portainer template.</p></body></html>" > /usr/share/nginx/html/index.html &&
        nginx -g "daemon off;"
      '