version: "3.8"

volumes:
  grafana-data: {}
  clickhouse-data: {}

networks:
  monitoring-net:
    driver: bridge

services:
  # Grafana (unchanged)
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "${GRAFANA_PORT}:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - monitoring-net
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}

  # ClickHouse database with corrected entrypoint
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-server
    hostname: clickhouse-server
    restart: unless-stopped
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    networks:
      - monitoring-net
    environment:
      CLICKHOUSE_USER: ${CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
      S3_HOST: ${S3_HOST:-}
      S3_BUCKET: ${S3_BUCKET:-}
      S3_PREFIX: ${S3_PREFIX:-}
      S3_KEY: ${S3_KEY:-}
      S3_SECRET: ${S3_SECRET:-}
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    entrypoint:
      - /bin/sh
      - -c
      - |
        set -e
        CONFIG_FILE="/etc/clickhouse-server/config.d/storage.xml"

        # Check if S3 environment variables are set and not empty
        if [ -n "$S3_HOST" ] && [ -n "$S3_BUCKET" ] && [ -n "$S3_KEY" ] && [ -n "$S3_SECRET" ]; then
            echo "S3 credentials found. Generating S3 storage configuration."
            
            # Use a heredoc to create the storage configuration file
            # Backslashes MUST be double-escaped (\\) for YAML multi-line strings
            cat > "$CONFIG_FILE" <<EOF
        <clickhouse>
          <storage_configuration>
            <disks>
                <default>
                    <keep_free_space_bytes>21474836480</keep_free_space_bytes>
                </default>
                <s3_storage>
                    <type>s3</type>
                    <endpoint>\\${S3_HOST}/\\${S3_BUCKET}/\\${S3_PREFIX:-}</endpoint>
                    <access_key_id>\\${S3_KEY}</access_key_id>
                    <secret_access_key>\\${S3_SECRET}</secret_access_key>
                    <metadata_path>/var/lib/clickhouse/s3_metadata/</metadata_path>
                    <cache_enabled>true</cache_enabled>
                    <data_cache_enabled>true</data_cache_enabled>
                    <cache_path>/var/lib/clickhouse/s3_cache/</cache_path>
                    <max_cache_size>2Gi</max_cache_size>
                    <thread_pool_size>100</thread_pool_size>
                </s3_storage>
            </disks>
            <policies>
                <tiered>
                    <volumes>
                        <default>
                            <disk>default</disk>
                            <volume_priority>1</volume_priority>
                        </default>
                        <s3>
                            <disk>s3_storage</disk>
                            <prefer_not_to_merge>false</prefer_not_to_merge>
                            <perform_ttl_move_on_insert>false</perform_ttl_move_on_insert>
                            <volume_priority>2</volume_priority>
                        </s3>
                    </volumes>
                    <move_factor>0.05</move_factor>
                </tiered>
            </policies>
          </storage_configuration>
        </clickhouse>
        EOF
            echo "Configuration file '$CONFIG_FILE' created."
        else
            echo "S3 credentials not found. Skipping S3 storage configuration."
            rm -f "$CONFIG_FILE"
        fi

        # Execute the original ClickHouse entrypoint script
        exec /entrypoint.sh
    healthcheck:
      test:
        ["CMD", "wget", "--spider", "-q", "http://clickhouse-server:8123/ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Gigapipe services (unchanged)
  gigapipe-init:
    image: ghcr.io/metrico/gigapipe:v4.0.21
    container_name: gigapipe-init
    restart: "no"
    networks:
      - monitoring-net
    environment:
      CLICKHOUSE_SERVER: "clickhouse-server"
      CLICKHOUSE_AUTH: "${CLICKHOUSE_USER}:${CLICKHOUSE_PASSWORD}"
      PORT: "9080"
      MODE: "init_only"
    depends_on:
      clickhouse:
        condition: service_healthy

  gigapipe-writer:
    image: ghcr.io/metrico/gigapipe:v4.0.21
    container_name: gigapipe-writer
    hostname: gigapipe-writer
    restart: unless-stopped
    ports:
      - "${WRITER_PORT}:9080"
    networks:
      - monitoring-net
    environment:
      CLICKHOUSE_SERVER: "clickhouse-server"
      CLICKHOUSE_AUTH: "${CLICKHOUSE_USER}:${CLICKHOUSE_PASSWORD}"
      PORT: "9080"
      MODE: "writer"
    depends_on:
      gigapipe-init:
        condition: service_completed_successfully

  gigapipe-reader:
    image: ghcr.io/metrico/gigapipe:v4.0.21
    container_name: gigapipe-reader
    hostname: gigapipe-reader
    restart: unless-stopped
    ports:
      - "${READER_PORT}:9080"
    networks:
      - monitoring-net
    environment:
      CLICKHOUSE_SERVER: "clickhouse-server"
      CLICKHOUSE_AUTH: "${CLICKHOUSE_USER}:${CLICKHOUSE_PASSWORD}"
      PORT: "9080"
      MODE: "reader"
    depends_on:
      gigapipe-init:
        condition: service_completed_successfully
