version: "3.8"

networks:
  monitoring-net:
    driver: bridge

services:
  # Grafana for data visualization
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "${GRAFANA_PORT}:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - monitoring-net
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}

  # ClickHouse database
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-server
    hostname: clickhouse-server
    restart: unless-stopped
    ports:
      - "8123:8123" # HTTP interface
      - "9000:9000" # Native client interface
    volumes:
      - ${CLICKHOUSE_DATA_PATH}:/var/lib/clickhouse
    networks:
      - monitoring-net
    environment:
      CLICKHOUSE_USER: ${CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    # Add a healthcheck so other services can wait for it to be ready
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8123/ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  # New service to initialize the database schema and then exit
  gigapipe-init:
    image: gigapipe:latest
    container_name: gigapipe-init
    restart: "no" # Do not restart this container; it's a one-shot task
    networks:
      - monitoring-net
    environment:
      CLICKHOUSE_SERVER: "clickhouse-server"
      CLICKHOUSE_AUTH: "${CLICKHOUSE_USER}:${CLICKHOUSE_PASSWORD}"
      PORT: "9080"
      MODE: "init_only"
    depends_on:
      clickhouse:
        condition: service_healthy # Wait for ClickHouse to pass its healthcheck

  # Gigapipe service in "writer" mode
  gigapipe-writer:
    image: gigapipe:latest
    container_name: gigapipe-writer
    hostname: gigapipe-writer
    restart: unless-stopped
    ports:
      - "${WRITER_PORT}:9080"
    networks:
      - monitoring-net
    environment:
      CLICKHOUSE_SERVER: "clickhouse-server"
      CLICKHOUSE_AUTH: "${CLICKHOUSE_USER}:${CLICKHOUSE_PASSWORD}"
      PORT: "9080"
      MODE: "writer"
    depends_on:
      gigapipe-init:
        # Wait for the init container to complete successfully (exit code 0)
        condition: service_completed_successfully

  # Gigapipe service in "reader" mode
  gigapipe-reader:
    image: gigapipe:latest
    container_name: gigapipe-reader
    hostname: gigapipe-reader
    restart: unless-stopped
    ports:
      - "${READER_PORT}:9080"
    networks:
      - monitoring-net
    environment:
      CLICKHOUSE_SERVER: "clickhouse-server"
      CLICKHOUSE_AUTH: "${CLICKHOUSE_USER}:${CLICKHOUSE_PASSWORD}"
      PORT: "9080"
      MODE: "reader"
    depends_on:
      gigapipe-init:
        # Also wait for the init container to complete successfully
        condition: service_completed_successfully

volumes:
  grafana-data:
